#!/usr/bin/env ruby

require 'fileutils'
include FileUtils

myid = Integer(ENV['MYID'])
nodes = ENV['ZOOKEEPER_NODES'].split(',')

open('/etc/zookeeper/conf/myid', 'wb') { |f| f.write(myid) }

cp('/etc/zookeeper/conf/zoo.cfg', '/tmp/zoo.cfg')
open('/tmp/zoo.cfg', 'ab') { |f|
  nodes.each_with_index { |z, idx|
    idx += 1
    f.write("server.#{idx}=#{z}:2888:3888\n")
  }
}

cp('/tmp/zoo.cfg', '/etc/zookeeper/conf/zoo.cfg')

exec('/usr/share/zookeeper/bin/zkServer.sh start-foreground')

