#!/usr/bin/env ruby

require 'fileutils'
include FileUtils

zoo_nodes = ENV['ZOOKEEPER_NODES'].split(',') rescue abort('No zookeeper nodes!')

# Convert KAFKA_BROKER_ID=1 to broker.id=1
settings = ENV.select { |k, v|
  k.start_with?('KAFKA_')
}.map { |k,v|
  [k.gsub(/^KAFKA_/, '').downcase.gsub('_', '.'), v]
}

settings = Hash[*settings.flatten(1)]
settings['zookeeper.connect'] = zoo_nodes.join(',')

open('/etc/kafka/server.properties') { |r|
  open('/tmp/server.properties', 'w') { |w|
    r.each_line { |l|
      next if l.start_with? '#'
      next if settings[l.split('=').first]
      w.write(l)
    }

    w.puts

    settings.each { |k, v|
      w.puts("#{k}=#{v}")
    }
  }
}
cp('/tmp/server.properties', '/etc/kafka/server.properties')

exec('/usr/bin/kafka-server-start /etc/kafka/server.properties')

